<a href="https://colab.research.google.com/github/DajeanArcila/biblioteca_pandas/blob/main/desafio_data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Desafio 5.

In [ ]:
!pip install pandas

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [27]:
dataset = pd.read_csv('data.csv', encoding='ISO-8859-1')
dataset.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [29]:
dataset.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [39]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [40]:
dataset.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [48]:
dataset= dataset.dropna()

In [49]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  object
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.9+ MB

In [51]:
dataset.describe()

            Quantity      UnitPrice     CustomerID
count  406829.000000  406829.000000  406829.000000
mean       12.061303       3.460471   15287.690570
std       248.693370      69.315162    1713.600303
min    -80995.000000       0.000000   12346.000000
25%         2.000000       1.250000   13953.000000
50%         5.000000       1.950000   15152.000000
75%        12.000000       3.750000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [60]:
nulos = dataset['UnitPrice'].isnull().any()
print(nulos)

False

In [65]:
menor_que_0 = (dataset['UnitPrice'] < 0).any()
print(menor_que_0)

False

In [75]:
nulos_q= (dataset['Quantity']<0).sum()
print(nulos_q)

8905

In [132]:
df = dataset[dataset['Quantity'] > 0]
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[397924 rows x 8 columns]

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  object
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  float64
 7   Country      397924 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.3+ MB

In [134]:
duplicadas= df.duplicated()

In [135]:
print("Filas duplicadas:")
print(df[duplicadas])

Filas duplicadas:
       InvoiceNo StockCode                        Description  Quantity  \
517       536409     21866        UNION JACK FLAG LUGGAGE TAG         1
527       536409     22866      HAND WARMER SCOTTY DOG DESIGN         1
537       536409     22900    SET 2 TEA TOWELS I LOVE LONDON          1
539       536409     22111       SCOTTIE DOG HOT WATER BOTTLE         1
555       536412     22327  ROUND SNACK BOXES SET OF 4 SKULLS         1
...          ...       ...                                ...       ...
541675    581538     22068        BLACK PIRATE TREASURE CHEST         1
541689    581538     23318     BOX OF 6 MINI VINTAGE CRACKERS         1
541692    581538     22992             REVOLVER WOODEN RULER          1
541699    581538     22694                       WICKER STAR          1
541701    581538     23343       JUMBO BAG VINTAGE CHRISTMAS          1

            InvoiceDate  UnitPrice  CustomerID         Country
517     12/1/2010 11:45       1.25     17908.0  United Kingdom
527     12/1/2010 11:45       2.10     17908.0  United Kingdom
537     12/1/2010 11:45       2.95     17908.0  United Kingdom
539     12/1/2010 11:45       4.95     17908.0  United Kingdom
555     12/1/2010 11:49       2.95     17920.0  United Kingdom
...                 ...        ...         ...             ...
541675  12/9/2011 11:34       0.39     14446.0  United Kingdom
541689  12/9/2011 11:34       2.49     14446.0  United Kingdom
541692  12/9/2011 11:34       1.95     14446.0  United Kingdom
541699  12/9/2011 11:34       2.10     14446.0  United Kingdom
541701  12/9/2011 11:34       2.08     14446.0  United Kingdom

[5192 rows x 8 columns]

In [136]:
df_limpo = df.drop_duplicates()

In [142]:
df['CustomerID'] = df['CustomerID'].astype(int)
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

<ipython-input-142-194cca8f2572>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CustomerID'] = df['CustomerID'].astype(int)
<ipython-input-142-194cca8f2572>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397924 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397924 non-null  object
 1   StockCode    397924 non-null  object
 2   Description  397924 non-null  object
 3   Quantity     397924 non-null  int64
 4   InvoiceDate  397924 non-null  datetime64[ns]
 5   UnitPrice    397924 non-null  float64
 6   CustomerID   397924 non-null  int64
 7   Country      397924 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 27.3+ MB

In [144]:
outliers = df[(df['Quantity'] > 10000) | (df['UnitPrice'] > 5000)]

# Imprimir os outliers
print("Outliers:")
print(outliers)

Outliers:
       InvoiceNo StockCode                     Description  Quantity  \
61619     541431     23166  MEDIUM CERAMIC TOP STORAGE JAR     74215
173382    551697      POST                         POSTAGE         1
502122    578841     84826  ASSTD DESIGN 3D PAPER STICKERS     12540
540421    581483     23843     PAPER CRAFT , LITTLE BIRDIE     80995

               InvoiceDate  UnitPrice  CustomerID         Country
61619  2011-01-18 10:01:00       1.04       12346  United Kingdom
173382 2011-05-03 13:46:00    8142.75       16029  United Kingdom
502122 2011-11-25 15:57:00       0.00       13256  United Kingdom
540421 2011-12-09 09:15:00       2.08       16446  United Kingdom

In [146]:
df = df[(df['Quantity'] <= 10000) & (df['UnitPrice'] <= 5000)]

In [147]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397920 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397920 non-null  object
 1   StockCode    397920 non-null  object
 2   Description  397920 non-null  object
 3   Quantity     397920 non-null  int64
 4   InvoiceDate  397920 non-null  datetime64[ns]
 5   UnitPrice    397920 non-null  float64
 6   CustomerID   397920 non-null  int64
 7   Country      397920 non-null  object
 8   TotalPrice   397920 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 30.4+ MB

In [150]:
fecha_ultima_compra = df['InvoiceDate'].max()

In [153]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34